[tool.black]
line-length = 120
target-version = ['py311']
skip-string-normalization = false

[tool.ruff]
line-length = 120
target-version = "py311"
lint.select = ["E", "F", "I", "B"]
lint.fixable = ["ALL"]

[tool.ruff.lint.isort]
force-single-line = false
known-first-party = ["easy-news"]
